- .github/workflows/make-image.yml
- just aligned for RPi and Generic atm
> upload to device folder $version/$project/$device

- .github/workflows/make-image.yml
As DEVICE is set as blank in LE10 - set it to "Generic" and some minor code tidies.
> make-image: set the DEVICE to Generic

- .github/workflows/build-images.yml
Support build of R40 - https://github.com/LibreELEC/LibreELEC.tv/issues/6814
> build-images.yml: build nightlies for Allwinner R40

- .github/workflows/tools-update-changelog.yml
- .gitmodules
- updates releases.json at nightlies
- added git submodule for https://github.com/LibreELEC/release-scripts that host that script
- `time python3` to get an idea how long the script actually works
> scripts: update  releases.json at test.le.tv

- .github/workflows/nightly-LE10.yml
> build-images.yml: fix R40

- .github/workflows/nightly-LE11-addons.yml
- .github/workflows/nightly-LE11.yml
I am not too sure if I missed something.
I just copied master image + addons and renamed to LE11 and removed stuff we do not need anyway.
> add files for LE11

- .github/workflows/nightly-LE10-addons.yml
- .github/workflows/nightly-LE10.yml
disable automatic building (nightlies) for LE10
> disable cron building (nightlies) for LE10

- .github/workflows/nightly-MASTER-addons.yml
Enable addon builds for aarch64
> nightly-MASTER-addons.yml: build ARMv8.aarch64 addons

- .github/workflows/build-images.yml
- .github/workflows/nightly-MASTER-addons.yml
> switch master to LE12

- .github/workflows/nightly-LE11-addons.yml
- .github/workflows/nightly-LE11.yml
no idea why I did it THAT wrong before, pls have a look if anyone spots anything at the diff
> fixes LE11 builds

- .github/workflows/update-cacert-pem-certificate-bundle.yml
- https://github.com/peter-evans/create-pull-request/blob/main/docs/updating.md
- https://github.com/peter-evans/create-pull-request/releases
> update-cacert-pem-certificate-bundle.yml: update create-pull-request to v5

- .github/workflows/tools-cleanup-images.yml
testrun looks okay, so lets start deleting
> tools-cleanup-images: enable delete

- .github/workflows/create-addon.yml
- .github/workflows/make-image.yml
- tested with tidied up :jammy from https://github.com/LibreELEC/LibreELEC.tv/pull/7898
> docker: migrate workflows to ubuntu:jammy

- .github/workflows/create-addon.yml
- .github/workflows/make-image.yml
ref:
- https://github.com/actions/upload-artifact#customization-if-no-files-are-found
> do not warn if there are no artifacts for upload

- .github/workflows/build-images.yml
- .github/workflows/create-addon.yml
- .github/workflows/make-image.yml
- .github/workflows/nightly-LE10-addons.yml
- .github/workflows/nightly-LE10.yml
- .github/workflows/nightly-LE11-addons.yml
- .github/workflows/nightly-LE11.yml
- .github/workflows/nightly-MASTER-addons.yml
- .github/workflows/tools-cleanup-images.yml
- .github/workflows/tools-update-addon-repo.yml
- .github/workflows/tools-update-changelog.yml
- .github/workflows/update-cacert-pem-certificate-bundle.yml
Remove hardcoded user/actor/repositories
> update workflows to be generic to enable their running in a fork

- .github/workflows/build-images.yml
- .github/workflows/create-addon.yml
- .github/workflows/make-image.yml
- .github/workflows/nightly-LE10-addons.yml
- .github/workflows/nightly-LE10.yml
- .github/workflows/nightly-LE11-addons.yml
- .github/workflows/nightly-LE11.yml
- .github/workflows/nightly-MASTER-addons.yml
- .github/workflows/tools-cleanup-images.yml
- .github/workflows/tools-update-addon-repo.yml
- .github/workflows/tools-update-changelog.yml
- .github/workflows/update-cacert-pem-certificate-bundle.yml
github.actor resolves to the committer, not the repo
> revert github.actor back to LibreELEC

- .github/workflows/build-images.yml
- .github/workflows/create-addon.yml
- .github/workflows/make-image.yml
- .github/workflows/nightly-LE10-addons.yml
- .github/workflows/nightly-LE10.yml
- .github/workflows/nightly-LE11-addons.yml
- .github/workflows/nightly-LE11.yml
- .github/workflows/nightly-MASTER-addons.yml
- .github/workflows/tools-cleanup-images.yml
- .github/workflows/tools-update-addon-repo.yml
- .github/workflows/tools-update-changelog.yml
- .github/workflows/update-cacert-pem-certificate-bundle.yml
Update from LibreELEC to ${{ github.repository_owner }} to allow fork to run the actions repo against the repository_owner/LibreELEC.tv source.
> use github.repository_owner for the checked out repository owner

- .github/workflows/nightly-LE11.yml
Single missing -11_0 causing build conflict
> nightly-LE11.yml: fix group for R40_arm

- .github/workflows/nightly-LE11.yml
Dependent on
- https://github.com/LibreELEC/LibreELEC.tv/pull/8181
> Add support for RPi5 In LE11

- .github/workflows/nightly-MASTER-addons.yml
> nightly-MASTER-addons: drop build of ARMv8.arm addons

- .github/workflows/make-image.yml
Only set the NOOBS= env variable for RPi project, and upload the sha256 files for tar/ova (fixes #39).
> make-image updates

- .github/workflows/update-cacert-pem-certificate-bundle.yml
Fixes nodejs 16 warning
ref:
- https://github.com/peter-evans/create-pull-request/releases/tag/v6.0.0
> update peter-evans/create-pull-request to v6

- .github/workflows/build-LE12-addons.yml
- .github/workflows/build-LE12.yml
- .github/workflows/build-LE13-addons.yml
- .github/workflows/build-LE13.yml
- .github/workflows/yml-uses-create-addon-LE13.yml
- .github/workflows/yml-uses-make-image-LE13.yml
- update LE12 scripts to use gitref: libreelec-12.0
- Add LE13 build scripts
> Update actions for LE12 to use githash:libreeelec-12.0 and LE12 to use githash:master

- .github/workflows/tools-cleanup-images.yml
- .github/workflows/tools-update-addon-repo.yml
- tools-cleanup-images: add cleanups for LE12 and LE13 for 200 nightlies each
- tools-update-addon-repo: default to 12.0.0
> update the tools- for LE12 change

- .github/workflows/yml-uses-create-addon-LE13.yml
- .github/workflows/yml-uses-make-image-LE13.yml
Update to latest Ubuntu LTS for LE13 addon and LE13 image builds
> use Ubuntu 24.04 (Noble Numbat) for LE13 builds

- .github/workflows/yml-uses-make-image-LE13.yml
- list files in target
- always list the files in the /target/ directory after build
- do not upload files if the secrets.NIGHTLY_HOST is not set
- even if upload is set (don’t upload the /target/ files if the ssh server is not set
> Improvements when running in a fork

- .github/workflows/yml-uses-create-addon-LE13.yml
> do not upload files if the secrets.ADDONS_HOST is not set

- .github/workflows/build-LE12.yml
don't build LE12 nightlies for projects we are not releasing
> drop unreleased projects for LE12

- .github/workflows/build-LE12-2-addons.yml
- .github/workflows/build-LE12-2.yml
- .github/workflows/yml-uses-create-addon-LE12-2.yml
- .github/workflows/yml-uses-make-image-LE12-2.yml
> Add LE12.2 build scripts

- .github/workflows/build-LE10-addons.yml
- .github/workflows/build-LE10.yml
- .github/workflows/build-LE11-addons.yml
- .github/workflows/build-LE11.yml
- .github/workflows/build-LE12-2-addons.yml
- .github/workflows/build-LE12-2.yml
- .github/workflows/build-LE12-addons.yml
- .github/workflows/build-LE12.yml
- .github/workflows/build-LE13-addons.yml
- .github/workflows/build-LE13.yml
- .github/workflows/tools-check-yaml.yml
- .github/workflows/tools-cleanup-images.yml
- .github/workflows/tools-update-addon-repo.yml
- .github/workflows/tools-update-changelog.yml
- .github/workflows/update-cacert-pem-certificate-bundle.yml
- .github/workflows/yml-uses-create-addon-LE10.yml
- .github/workflows/yml-uses-create-addon-LE11.yml
- .github/workflows/yml-uses-create-addon-LE12-2.yml
- .github/workflows/yml-uses-create-addon-LE12.yml
- .github/workflows/yml-uses-create-addon-LE13.yml
- .github/workflows/yml-uses-make-image-LE10.yml
- .github/workflows/yml-uses-make-image-LE11.yml
- .github/workflows/yml-uses-make-image-LE12-2.yml
- .github/workflows/yml-uses-make-image-LE12.yml
- .github/workflows/yml-uses-make-image-LE13.yml
https://github.com/actions/checkout/blob/main/CHANGELOG.md
> update to actions/checkout@v5

- .github/workflows/tools-update-changelog.yml
Reduce frequency of update of changelog to every 12 hours, down from every 2 hours
> Reduce frequency to every 12 hours
